# Generated by Django 4.1.7 on 2023-04-21 05:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lista', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fracciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerador', models.IntegerField()),
                ('denominador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pregunta', models.CharField(max_length=30)),
                ('fraccion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_fraccion1', to='game.fracciones')),
                ('fraccion2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_fraccion2', to='game.fracciones')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_resultado', to='game.fracciones')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.alumno')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.preguntas')),
                ('respuesta_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.fracciones')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='game.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='game.grupo'),
        ),
        migrations.CreateModel(
            name='Ajustes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.IntegerField()),
                ('dificultad', models.CharField(max_length=1)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.alumno')),
            ],
        ),
    ]
