# Generated by Django 4.1.7 on 2023-04-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='nivel_actual',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='num_lista',
            field=models.IntegerField(),
        ),
    ]
