# Generated by Django 4.1.7 on 2023-04-21 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alumno_nivel_actual_alter_alumno_num_lista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntas',
            name='fraccion1',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='fraccion2',
        ),
        migrations.RemoveField(
            model_name='preguntas',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuestas',
            name='respuesta_alumno',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='game.grupo'),
        ),
        migrations.DeleteModel(
            name='Fracciones',
        ),
        migrations.DeleteModel(
            name='Preguntas',
        ),
        migrations.DeleteModel(
            name='Respuestas',
        ),
    ]
