# Generated by Django 4.1.7 on 2023-04-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alumno_aciertos_n3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='aciertos_n3',
        ),
        migrations.CreateModel(
            name='Intentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciertos', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='game.alumno')),
            ],
        ),
    ]
