# Generated by Django 4.1.7 on 2023-05-03 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_alumno_aciertos_n3_intentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equivocaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='intentos',
            name='nivel',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.grupo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.profesor'),
        ),
        migrations.AlterField(
            model_name='intentos',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.alumno'),
        ),
        migrations.DeleteModel(
            name='Ajustes',
        ),
        migrations.AddField(
            model_name='equivocaciones',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.alumno'),
        ),
    ]
