# Generated by Django 4.1.7 on 2023-05-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_alumno_aciertos_n3_intentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentos',
            name='nivel',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
